version: '3'

services:
  tiger:
    image: ghcr.io/kwenoch/tiger:${TIGER_VERSION:-latest}
    restart: unless-stopped
    env_file: .env
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    networks:
      - tiger
    ports:
      - ${TIGER_HTTP_PORT:-8080}:8080

networks:
  tiger:
    enable_ipv6: true
