version: '3'

services:
  caddy:
    image: caddy:${CADDY_VERSION:-latest}
    restart: unless-stopped
    env_file: .env
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    volumes:
      - type: bind
        source: ${CADDY_APP_ROOT:-/opt/persistent-storage/caddy/app/site}
        target: /srv
      - ${CADDY_CONF_ROOT:-/opt/persistent-storage/caddy/app/conf}:/etc/caddy
      - ${CADDY_TEMP_ROOT:-/opt/persistent-storage/caddy/app/temp}/data:/data
      - ${CADDY_TEMP_ROOT:-/opt/persistent-storage/caddy/app/temp}/config:/config
    networks:
      - caddy
    ports:
      - ${CADDY_HTTP_PORT:-80}:80/tcp
      - ${CADDY_HTTPS_PORT:-443}:443/tcp
      - ${CADDY_HTTPS_PORT:-443}:443/udp
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  caddy:
    enable_ipv6: true
